export const attendanceStats = {
  present: 198,
  absent: 12,
  late: 24,
  onLeave: 11,
  avgHours: "8h 15m"
};

export const attendanceData = [
  {
    id: "att-1",
    employee: "Alex Kumar",
    avatar: "AK",
    department: "Engineering",
    checkIn: "08:55 AM",
    checkOut: "05:15 PM",
    totalHours: "8h 20m",
    status: "Present",
  },
  {
    id: "att-2",
    employee: "Sarah Chen",
    avatar: "SC",
    department: "Engineering",
    checkIn: "09:30 AM",
    checkOut: "06:45 PM",
    totalHours: "9h 15m",
    status: "Late",
  },
  {
    id: "att-3",
    employee: "Marcus Johnson",
    avatar: "MJ",
    department: "Product",
    checkIn: "-",
    checkOut: "-",
    totalHours: "-",
    status: "On Leave",
  },
  {
    id: "att-4",
    employee: "Emily Davis",
    avatar: "ED",
    department: "Design",
    checkIn: "08:45 AM",
    checkOut: "05:00 PM",
    totalHours: "8h 15m",
    status: "Present",
  },
  {
    id: "att-5",
    employee: "Michael Chang",
    avatar: "MC",
    department: "HR",
    checkIn: "-",
    checkOut: "-",
    totalHours: "-",
    status: "Absent",
  },
  {
    id: "att-6",
    employee: "Jessica Smith",
    avatar: "JS",
    department: "Marketing",
    checkIn: "09:05 AM",
    checkOut: "05:30 PM",
    totalHours: "8h 25m",
    status: "Present",
  },
  {
    id: "att-7",
    employee: "David Wilson",
    avatar: "DW",
    department: "Sales",
    checkIn: "10:15 AM",
    checkOut: "07:00 PM",
    totalHours: "8h 45m",
    status: "Late",
  }
];
