"use client"

import React from "react"
import { FileText, Download, TrendingUp, Users, Calendar, DollarSign, ShieldCheck, Play } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

const reportTemplates = [
  { title: "Attendance Summary", category: "Operations", icon: Calendar, desc: "Biometric attendance and leave utilization analysis." },
  { title: "Payroll Report", category: "Finance", icon: DollarSign, desc: "Monthly salary expenditure and tax withholdings." },
  { title: "Leave Balance Report", category: "Operations", icon: TrendingUp, desc: "Employee leave balance and accruals." },
  { title: "Employee Directory", category: "Workforce", icon: Users, desc: "Detailed breakdown of employee demographic data." },
]

export default function ReportsPage() {
  return (
    <div className="flex-1 space-y-4 p-4 md:p-8 pt-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between space-y-2 sm:space-y-0">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Reports & Analytics Engine</h2>
          <p className="text-muted-foreground mt-1">Export executive workforce reports, compliance audits, and custom data filters.</p>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Generated Reports</CardTitle>
            <FileText className="h-4 w-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">0</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Scheduled Reports</CardTitle>
            <Calendar className="h-4 w-4 text-emerald-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">0</div>
          </CardContent>
        </Card>
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-4">Available Reports</h3>
      <div className="grid gap-6 md:grid-cols-2">
        {reportTemplates.map((report, i) => (
          <Card key={i} className="hover:border-primary/50 transition-colors">
            <CardHeader className="flex flex-row items-start justify-between space-y-0">
              <div className="space-y-1">
                <Badge variant="outline" className="mb-2">{report.category}</Badge>
                <CardTitle className="text-xl">{report.title}</CardTitle>
              </div>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary shrink-0">
                <report.icon className="h-5 w-5" />
              </div>
            </CardHeader>
            <CardContent>
              <CardDescription className="text-sm text-muted-foreground leading-relaxed">
                {report.desc}
              </CardDescription>
              <div className="flex gap-2 mt-6">
                <Button size="sm" className="bg-primary flex-1">
                  <Play className="mr-2 h-4 w-4" /> Generate Report
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-4">Recently Generated Reports</h3>
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell colSpan={4} className="h-24 text-center text-muted-foreground">
                  No recently generated reports
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
