export const employeesData = [
  {
    id: "EMP-1001",
    name: "Ankit Sethi",
    email: "Ankit.sethi@kenzoinfosystems.com",
    department: "Executive Management",
    designation: "CEO & Founder",
    status: "Active",
    joinDate: "2020-01-01",
  },
  {
    id: "EMP-1002",
    name: "Sujal Kumar",
    email: "Sujal.kumar@kenzoinfosystems.com",
    department: "Engineering & Technology",
    designation: "Software Engineer",
    status: "Active",
    joinDate: "2024-01-15",
  },
  {
    id: "EMP-1003",
    name: "Chanchal Saini",
    email: "Chanchal.saini@kenzoinfosystems.com",
    department: "Administration",
    designation: "Managing Director",
    status: "Active",
    joinDate: "2026-08-07",
  },
  {
    id: "EMP-1004",
    name: "Jitender Saini",
    email: "Jitender.saini@kenzoinfosystems.com",
    department: "Administration",
    designation: "CEO",
    status: "Active",
    joinDate: "2026-08-07",
  },
  {
    id: "EMP-1005",
    name: "Laxmi Narayan",
    email: "Laxminarayan.ojha@kenzoinfosystems.com",
    department: "Sales & Field Services",
    designation: "Field Sales Executive",
    status: "Active",
    joinDate: "2026-08-06",
  },
]
