export const employeesData = [
  {
    id: "EMP-001",
    name: "John Doe",
    email: "john.doe@kenzo.com",
    department: "Engineering",
    designation: "Senior Frontend Engineer",
    status: "Active",
    joinDate: "2020-03-15",
  },
  {
    id: "EMP-002",
    name: "Jane Smith",
    email: "jane.smith@kenzo.com",
    department: "Product",
    designation: "Product Manager",
    status: "Active",
    joinDate: "2021-06-01",
  },
  {
    id: "EMP-003",
    name: "Michael Johnson",
    email: "michael.j@kenzo.com",
    department: "Engineering",
    designation: "Backend Developer",
    status: "On Leave",
    joinDate: "2022-01-10",
  },
  {
    id: "EMP-004",
    name: "Emily Davis",
    email: "emily.d@kenzo.com",
    department: "Design",
    designation: "UX Designer",
    status: "Active",
    joinDate: "2021-11-20",
  },
  {
    id: "EMP-005",
    name: "Robert Wilson",
    email: "robert.w@kenzo.com",
    department: "Sales",
    designation: "Account Executive",
    status: "Terminated",
    joinDate: "2019-05-12",
  },
]
