export const mockEmployee = {
  id: "EMP-1002",
  firstName: "Sujal",
  lastName: "Kumar",
  email: "employee@kenzo.com",
  phone: "+91 98765 43210",
  department: "Engineering",
  designation: "Software Architect",
  status: "Active",
  joinDate: "2024-01-15",
  manager: "Ankit Sethi",
  location: "Noida, India",
  address: "Sector 62, Noida, Uttar Pradesh 201301",
  dob: "1998-05-22",
  gender: "Male",
  maritalStatus: "Single",
  emergencyContact: {
    name: "Rahul Kumar",
    relation: "Brother",
    phone: "+91 91234 56789",
  },
  employmentHistory: [
    {
      title: "Software Architect",
      date: "2024-06-01 - Present",
      type: "Promotion",
    },
    {
      title: "Senior Software Engineer",
      date: "2024-01-15 - 2024-05-31",
      type: "New Hire",
    },
  ],
  salary: "₹18,00,000",
}

export const mockAdmin = {
  id: "EMP-1001",
  firstName: "Ankit",
  lastName: "Sethi",
  email: "admin@kenzo.com",
  phone: "+91 99876 54321",
  department: "Management",
  designation: "CEO & Founder",
  status: "Active",
  joinDate: "2020-01-01",
  manager: "-",
  location: "Noida, India",
  address: "Tech Hub, Sector 62, Noida, Uttar Pradesh 201301",
  dob: "1992-03-15",
  gender: "Male",
  maritalStatus: "Married",
  emergencyContact: {
    name: "Priya Sethi",
    relation: "Spouse",
    phone: "+91 98765 00000",
  },
  employmentHistory: [
    {
      title: "CEO & Founder",
      date: "2020-01-01 - Present",
      type: "Founder",
    },
  ],
  salary: "₹36,00,000",
}
